Dev
noelfoka/react-group-project pull request #35
Opened 2023-09-01 03:32 UTC by noelfoka

2023-09-01 04:30 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @noelfoka and @noelfoka 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Used React Router :heavy_check_mark: 
- Used React components :heavy_check_mark: 
- Used store, actions and reducers in React :heavy_check_mark:
- Used duck pattern structure for your files :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 04:30 UTC, tresorsawasawa commented on src/components/pages/Navbar.js
> +    },
- [ **OPTIONAL** ] I think it would be better if you remove the `Dragons` option from your your **Navbar** as you are a group of two persons and you didn't implement its/their content. This will ensure that your application looks completed, as right now when clicking on it, it displays an empty page. As result it shows your project as uncompleted.

2023-09-01 04:30 UTC, tresorsawasawa commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p> -->
- [ ] For clean code reasons and best practices, I think it would be better if you remove all the commented and unused code lines in all your code base.

2023-09-01 04:30 UTC, tresorsawasawa commented on README.md
> +
- [ ] Also, to make your documentation looks more professional and descriptive, I think it would be better if you complete each section with appropriate and correct information as for running your application, user should run the `npm run start` or `npm start` command

2023-09-01 04:30 UTC, tresorsawasawa commented on src/components/pages/Myprofile.js
> +);
- [ ] As required for the project to use the make layout like on the given wireframe, kindly ensure that you update the `My Profile` component to match the given template.
### Given Design
![my_profile](https://github.com/microverseinc/curriculum-react-redux/raw/main/group-project/images/space-travelers__my-profile.png)
### Your Design
![Screenshot from 2023-09-01 06-19-31](https://github.com/noelfoka/react-group-project/assets/83042742/83340bed-0408-42b6-831a-eccf212cb81a)

2023-09-01 04:30 UTC, tresorsawasawa commented on src/test/MissionsContainer.test.js
> +});
- [ ] As required for the project, kindly ensure that you add test for all your components and functions. Right now, I noticed that you only add tests on two components.
![Screenshot from 2023-09-01 06-26-13](https://github.com/noelfoka/react-group-project/assets/83042742/3eecc8f4-1084-47cb-a70a-4e931d3c8b0a)

2023-09-01 15:18 UTC, hetrox8 commented
Cahnges made :
1. Update Readme file
2. Removed Dragons pages
3. Write test for all pages components ( rockets, missions, profile)

2023-09-01 17:17 UTC, codecaiine requested changes
Hi @noelfoka @hetrox8 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good requested changes implementation start 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 17:17 UTC, codecaiine commented on src/components/pages/Rocket.js
> +          {list.map((each) => (
- [ ] Some of your tests are failed . As required for the project and requested by previous reviewer, Please make sure that you  all your components and functions are well implemented in the test   . Please fix it in order to make your test work as expected 👍 

![error_capt](https://github.com/noelfoka/react-group-project/assets/6615394/44656ad7-73f5-46d7-9672-69ad1d96c466)

2023-09-01 17:17 UTC, codecaiine commented on src/index.js
> +import React from 'react';
- [ ] Good job so far but when I ran your project I can only see blank page which make me not able to check the result of the implement about design requested by the previous reviewer . Please make sure that all your app pages work as expected 👍 

![index](https://github.com/noelfoka/react-group-project/assets/6615394/e503ef1e-d184-413d-84d4-729bf98497ff)

2023-09-01 17:39 UTC, hetrox8 commented on src/index.js
> +import React from 'react';
@codecaiine yes bro i would agree on this . kindly confirm  i am running it and its perfectly working

2023-09-02 00:14 UTC, vickymarz approved these changes
Hi @noelfoka , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 00:25 UTC, merged